#!/usr/bin/env bash

## Install ansible
DEBIAN_CODENAME=jammy
wget -O- "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367" | sudo gpg --dearmour -o /usr/share/keyrings/ansible-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/ansible-archive-keyring.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu $DEBIAN_CODENAME main" | sudo tee /etc/apt/sources.list.d/ansible.list

sudo apt update
sudo apt install curl git software-properties-common ansible

## pull ansible
sudo ansible-pull -U https://github.com/ladislaff93/ansible.git
sudo ansible-playbook local.yml --ask-vault-pass