#!/bin/bash

## Install ansible
sudo apt -y update
sudo apt -y install software-properties-common
sudo apt -y install curl
sudo apt -y install git
sudo apt -y install build-essential
sudo apt -y install wget
sudo apt -y update
sudo apt -y install ansible
sudo apt -y clean autoclean
sudo apt -y autoremove --yes

## run ansible
ansible-playbook local.yml --ask-vault-pass
