- hosts: localhost
  vars:
    main_user: "ladislaff"
    root_user: root
    source_key: "./.ssh/id_ed25519"
    dest_key: "/home/{{ main_user }}/.ssh/id_ed25519"
  become: true
  become_user: "{{ main_user }}"
  pre_tasks:
    - name: update repositories
      become: yes
      become_user: root
      apt: update_cache=yes
      changed_when: False
      tags:
        - awesome
        - bash
        - language
        - vim
        - vpn
        - ssh
        - fonts
  tasks:
    - block:
      - include_tasks: ./tasks/init_install.yml
      - include_tasks: ./tasks/install_ssh.yml
      - include_tasks: ./tasks/git_setup.yml
      - include_tasks: ./tasks/install_vscode.yml
      - include_tasks: ./tasks/install_chrome.yml
      - include_tasks: ./tasks/install_vpn.yml
      - include_tasks: ./tasks/bash.yml
      - include_tasks: ./tasks/wm.yml
      - include_tasks: ./tasks/dev_tasks.yml
      - include_tasks: ./tasks/app.yml
      - include_tasks: ./tasks/install_fonts.yml
      - include_tasks: ./tasks/firewall.yml
      - include_tasks: ./tasks/get_dotfiles.yml
      tags: always