- name: Install flatpak
  become: yes
  become_user: "{{ root_user }}"
  apt: name=flatpak
  tags:
    - apps
- name: Install obs flatpak
  become: yes
  become_user: "{{ root_user }}"
  flatpak: 
    name: https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
    state: present
    method: user
  tags:
    - apps
- name: Install spotify flatpak
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
    method: user
  tags:
    - apps
- name: Install Flameshot
  become: yes
  become_user: "{{ root_user }}"
  apt: name=flameshot
  tags:
    - apps
- name: Install qbittorrent
  become: yes
  become_user: "{{ root_user }}"
  apt: name=qbittorrent
  tags:
    - apps
- name: Install kitty
  become: yes
  become_user: "{{ root_user }}"
  apt: name=kitty
  tags:
    - apps
- name: Install btop
  become: yes
  become_user: "{{ root_user }}"
  apt: name=btop
  tags:
    - apps
- name: Install gimp
  become: yes
  become_user: "{{ root_user }}"
  apt: name=gimp
  tags:
    - apps
- name: Install vlc
  become: yes
  become_user: "{{ root_user }}"
  apt: name=vlc
  tags:
    - apps
- name: Install fzf
  become: yes
  become_user: "{{ root_user }}"
  apt: name=fzf
  tags:
    - apps
- name: Install tmux
  become: yes
  become_user: "{{ root_user }}"
  apt: name=tmux
  tags:
    - apps

- name: Install TMP plugin for tmux
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.git:
    repo: 'git@github.com:tmux-plugins/tpm.git'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    # accept_hostkey: yes
    accept_newhostkey: yes
    version: main

- name: Install Easy effects
  become: yes
  become_user: "{{ root_user }}"
  apt: name=easyeffects
  tags:
    - apps