- name: Install bash
  apt: name=bash
  tags:
    - bash
- name: Change shell
  shell: chsh -s 'which bash'
  tags:
    - bash
- name: Install Oh My Bash
  shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  tags:
    - bash

