
  # sudo add-apt-repository ppa:neovim-ppa/stable
  # sudo apt-get update
  # sudo apt-get install neovim
  # Need to intall newest neovim version
- name: Install Neovim 
  become: yes
  become_user: "{{ root_user }}"
  apt: name=neovim
  tags:
    - vim
- name: Install Rust
  become: yes
  become_user: "{{ root_user }}"
  shell: curl --proto '=https' -y --tlsv1.2 -sSf https://sh.rustup.rs | sh
  tags:
    - language
- name: Install Python
  become: yes
  become_user: "{{ root_user }}"
  apt: name=python3.11
  tags:
    - language
- name: Install Lua
  become: yes
  become_user: "{{ root_user }}"
  apt: name=lua5.1
  tags:
    - language
