- name: Git personal setup email
  become: yes
  become_user: "{{ main_user }}"
  git_config:
    name: user.email
    scope: global
    value: "lado93@gmail.com"
  tags:
  - git
- name: Git personal setup name
  become: yes
  become_user: "{{ main_user }}"
  git_config:
    name: user.name
    scope: global
    value: "ladislaff93"
  tags:
  - git
