- name: Install dependecies
  become: yes
  become_user: root
  apt: 
    name: [apt-transport-https, curl, gpg, git, fontconfig]
  tags:
    - awesome
    - bash
    - language
    - vim
    - vpn

- name: Update kernel
  become: yes
  become_user: root
  when: ansible_distribution == 'Debian'
  apt: 
    name: [linux-headers-amd64, linux-image-amd65]

- name: Adding sources into apt/sources.list 
  become: yes
  become_user: root
  when: ansible_distribution == 'Debian'
  blockinfile:
    path: /etc/apt/sources.list
    append_newline: true
    prepend_newline: true
    create: true
    block: |
      deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      deb-src http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      deb-src http://deb.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
      deb-src http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware

- name: Update apt 
  become: yes
  become_user: root
  when: ansible_distribution == 'Debian'
  apt: 
    update_cache: true

- name: Install Nvidia drivers
  become: yes
  become_user: root
  when: ansible_distribution == 'Debian'
  apt: 
    name: [nvidia-driver, firmware-misc-nonfree]

- name: Install drivers
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
  shell: sudo ubuntu-drivers install

- name: Install nvidia drivers
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
  apt: name=nvidia-driver-510
