- name: Check if fonts folder exists
  file:
    path: ~/.local/share/fonts
    state: directory
    mode: 0700
  tags:
    - fonts
- name: Install Nerd Font
  shell: curl -L -o "{{ lookup('env', 'HOME') }}/.local/share/fonts/Meslo.tar.xz" https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/Meslo.tar.xz
  tags:
    - fonts
- name: Extract Nerd font
  shell: tar -xvf "{{ lookup('env', 'HOME') }}/.local/share/fonts/Meslo.tar.xz"
  tags:
    - fonts
- name: Clear and regenerate font cache
  shell: fc-cache -f -v
  tags:
    - fonts
- name: Remove tarball file
  shell: rm "{{ lookup('env', 'HOME') }}/.local/share/fonts/Meslo.tar.xz"
  tags:
    - fonts