- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Install ssh key
  become: yes
  become_user: "{{ main_user }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - ssh
 
- name: Install ssh key public
  become: yes
  become_user: "{{ main_user }}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - ssh

- name: Add SSH Key to SSH Agent
  become: yes
  become_user: "{{ main_user }}"
  shell: eval "$(ssh-agent -s)" && ssh-add "/home/{{ main_user }}/.ssh/id_ed25519"

# - name: Set authorized key took from file
#   become: yes
#   become_user: "{{ main_user }}"
#   authorized_key:
#     user: "{{ main_user }}"
#     state: present
#     key: "/home/{{ main_user }}/.ssh/id_ed25519.pub"
#   with_fileglob:
#   - "/home/{{ main_user }}/.ssh/*.pub"