
- name: Extract Nerd font
  become: yes
  become_user: "{{ main_user }}"
  copy:
  src: "./fonts"
    dest: "/home/{{ main_user }}/.local/share/fonts/"
  tags:
    - fonts
     
- name: Clear and regenerate font cache
  become: yes
  become_user: "{{ root_user }}"
  shell: fc-cache -f -v
  tags:
    - fonts
