- name: Install Awesome WM
  apt: name=awesome
  tags:
    - awesome
- name: Install Picom
  apt: name=picom
  tags:
    - awesome
- name: Install i3lock-fancy
  apt: name=i3lock-fancy
  tags:
    - awesome
- name: Install nm applet && pnmixer
  apt: 
    name: [network-manager, pnmixer]
  tags:
    - awesome