- name: Install Awesome WM
  become: yes
  become_user: "{{ root_user }}"
  apt: name=awesome
  tags:
    - awesome
- name: Install Picom
  become: yes
  become_user: "{{ root_user }}"
  apt: name=picom
  tags:
    - awesome
- name: Install i3lock-fancy
  become: yes
  become_user: "{{ root_user }}"
  apt: name=i3lock-fancy
  tags:
    - awesome
- name: Install nm applet, pnmixer, lxde, xbacklight
  become: yes
  become_user: "{{ root_user }}"
  apt: 
    name: [network-manager, pnmixer, lxde, xbacklight]
  tags:
    - awesome

- name: Ensure directory exists.
  become: yes
  become_user: "{{ root_user }}"
  file:
    dest: /etc/X11/xorg.conf.d
    mode: 0777
    state: directory
  tags:
    - awesome

- name:  copy touchpad.conf file
  become: yes
  become_user: "{{ main_user }}"
  copy:
    src: ./30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
  tags:
    - awesome
